[versions]
apacheCommonsText = "1.12.0"
apiGuardian = "1.1.2"
equalsVerifier = "3.17.5"
gradleJavaConventions = "0.1.4"
hamcrest = "3.0"
jacoco = "0.8.8"
jqwik = "1.9.2"
junit = "5.11.3"
toStringVerifier = "1.4.8"

[libraries]
apiGuardian = { module = "org.apiguardian:apiguardian-api", version.ref = "apiGuardian" }
apacheCommonsText = { module = "org.apache.commons:commons-text", version.ref = "apacheCommonsText" }
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
jqwik = { module = "net.jqwik:jqwik", version.ref = "jqwik" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
toStringVerifier = { module = "com.jparams:to-string-verifier", version.ref = "toStringVerifier" }

[plugins]
gradleJavaConventions = { id = "com.opencastsoftware.gradle.java-conventions", version.ref = "gradleJavaConventions" }